jenkins:
  systemMessage: '<h1>Jenkins showcases. Dont use in production!</h1>'
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  disabledAdministrativeMonitors:
    - "com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.KubernetesCredentialProvider.initialize"
    - "hudson.model.UpdateCenter$CoreUpdateMonitor"
    - "jenkins.diagnostics.ControllerExecutorsNoAgents"
    - "jenkins.diagnostics.RootUrlNotSetMonitor"
    - "jenkins.security.s2m.MasterKillSwitchWarning"
    - "jenkins.diagnostics.ControllerExecutorsAgents"

  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

  slaveAgentPort: 50000

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

  sSHD:
    port: 40022

unclassified:
  themeManager:
    disableUserThemes: false
    theme: "material-indigo"

jobs:
  - script: >
      pipelineJob('smart-queue') {
          definition {
              cpsScm {
                  scm {
                      git {
                        remote {
                          name('origin')
                          url('https://github.com/livelace/jenkins-showcase.git')
                        }
                        branch('master')
                        extensions {}
                      }
                  }
                  scriptPath('showcase/smart-queue/pipeline/Jenkinsfile')
              }
          }
      }